version: "3.8"

services:
  postgres_hukum:
    image: postgres:15-alpine
    container_name: postgres_hukum
    restart: always
    environment:
      POSTGRES_USER: nvn
      POSTGRES_PASSWORD: tomato_hukum
      POSTGRES_DB: konsul_hukum
    ports:
      - "5434:5432"
    volumes:
      - postgres_hukum_data:/var/lib/postgresql/data
    networks:
      - hukum_network

  app_hukum:
    image: novn01/konsul-hukum-app:latest
    container_name: app_hukum
    restart: always
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/gcp-key.json
    volumes:
      - ./gcp-key.json:/app/secrets/gcp-key.json:ro
    depends_on:
      - postgres_hukum
    networks:
      - hukum_network
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.konsulhukum.rule=Host(`chat.nvnlab.space`)"
      - "traefik.http.routers.konsulhukum.entrypoints=websecure"
      - "traefik.http.routers.konsulhukum.tls=true"
      - "traefik.http.routers.konsulhukum.tls.certresolver=letsencrypt"
      - "traefik.http.services.konsulhukum.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  postgres_hukum_data:

networks:
  hukum_network:
  proxy:
    external: true
